language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.5.9
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit
