language: php

php:
  - 5.6
  - 7.0

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-source $PREFER_LOWEST

script:
  - phpunit
