language: php

matrix:
    include:
        - php:
            - 7.1
            - 7.2
            - 7.3
            - nightly
          env: TESTBENCH_VERSION=3.1.*
        - php:
            - 7.1
            - 7.2
            - 7.3
            - nightly
          env: TESTBENCH_VERSION=3.2.*
        - php:
            - 7.1
            - 7.2
            - 7.3
            - nightly
          env: TESTBENCH_VERSION=3.3.*
        - php:
            - 7.1
            - 7.2
            - 7.3
            - nightly
          env: TESTBENCH_VERSION=3.4.*
        - php:
            - 7.1
            - 7.2
            - 7.3
            - nightly
          env: TESTBENCH_VERSION=3.5.*
        - php:
            - 7.1
            - 7.2
            - 7.3
            - nightly
          env: TESTBENCH_VERSION=3.6.*
        - php:
            - 7.1
            - 7.2
            - 7.3
            - nightly
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - travis_retry composer self-update

install:
    - if [ ${TESTBENCH_VERSION} ]; then travis_retry composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update; fi
    - travis_retry composer install -n --no-suggest --prefer-dist

script:
    - php vendor/bin/phpunit
